### ISSUE TITLE
Terminal Component

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-gui#1]
It'd be nice to have a terminal component available that works similar to the terminal in the XTerm application.

**Comment by andersevenrud** [comment]
I'm using https://github.com/xtermjs/xterm.js in https://github.com/os-js/osjs-xterm-application.

Works great, and can work together with OS.js GUI and Hyperapp.

**Comment by andersevenrud** [comment]
Since making something like this is a pretty big job, I'll suggest looking into the xterm.js library for now.

I might re-open this in the future.
