### ISSUE TITLE
Using components in context menu

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-gui#3]

**Comment by andersevenrud** [comment]
![os js gui menu embed](https://user-images.githubusercontent.com/161548/49474380-d2889180-f814-11e8-84da-f3261deb22b3.png)

Coming in the next update :)

Example:
```
[{
  element: () => h('div', {}, 'Custom component'),
}, {
  label: 'Sub menu',
  items: [{
    element: () => h('div', {}, 'Custom component'),
  }]
}]
```

**Comment by andersevenrud** [comment]
I've published a new `@osjs/gui` release now.

This has been added and can be used as the example above. Let me know how it works out.
