### ISSUE TITLE
List don't render properly in Firefox

### ISSUE THREAD

**Issue by miladhashemi** [os-js/osjs-gui#31]
Hi,
In list view columns without values cause messing up .
![image](https://user-images.githubusercontent.com/5060331/85257816-ab87c400-b47b-11ea-9144-c3fdeab207e9.png)

> node v12.18.0
> hyperapp v1.2.10
> @osjs/gui v4.0.33

**Comment by andersevenrud** [comment]
I've released a new version of `@osjs/gui` that should solve your problem. Update this package and re-build your client.

**Comment by miladhashemi** [comment]
> I've released a new version of `@osjs/gui` that should solve your problem. Update this package and re-build your client.

Now it works properly.

**Comment by andersevenrud** [comment]
Great!
