### ISSUE TITLE
Select2 component in gui

### ISSUE THREAD

**Issue by miladhashemi** [os-js/osjs-gui#35]
Is there component similar to useful select2 (https://select2.org/) that be implemented in osjs-gu with hyperappi?

**Comment by andersevenrud** [comment]
No.

You can use select2 if you want though, even in Hyperapp.

**Comment by andersevenrud** [comment]
Btw, just an example of how to do this:

```
function createSelect2(rootElement) {
  // Use the root element
}
```

```
h('div', {
  oncreate: el => createSelect2(el)
})
```

or if you're using JSX:

```
<div oncreate={el => createSelect2(el)}></div>
```

**Comment by miladhashemi** [comment]
Thank U.
