### ISSUE TITLE
Selected tab doesn't show

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-gui#4]
Some sort of an inactive class needs to be applied to inactive tabs because there are no visible tabs.

**Comment by andersevenrud** [comment]
Care to illustrate, because I can't understand your description.

**Comment by SpaceboyRoss01** [comment]
Look the tab's contents arent showing even though there's code to make stuff show.  Care to illustrate, because I can't understand your description.

**Comment by SpaceboyRoss01** [comment]
![20181204-104549](https://user-images.githubusercontent.com/19699320/49465235-f4046180-f7b1-11e8-9702-5541385c7a44.png)

**Comment by andersevenrud** [comment]
This has been fixed in latest `@osjs/gui`.
